# SPDX-License-Identifier: MIT

#     Copyright (c) 2025 SUSE LLC

# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon.

# The content of THIS FILE IS AUTOGENERATED and should not be manually modified.
# It is maintained by the BCI team and generated by
# https://github.com/SUSE/BCI-dockerfile-generator

# Please submit bugfixes or comments via https://bugs.opensuse.org/
# You can contact the BCI team via https://github.com/SUSE/bci/discussions

#!UseOBSRepositories

#!BuildTag: rancher/image-build-kubernetes:v1.32.2
#!BuildTag: rancher/image-build-kubernetes:latest
#!BuildName: image-build-kubernetes

ARG BCI_IMAGE=registry.suse.com/bci/bci-base:15.5
ARG GO_IMAGE=rancher/image-build-base:latest


FROM ${BCI_IMAGE} as bci
FROM ${GO_IMAGE} as build
RUN set -euo pipefail; \
    zypper -n install --no-recommends \
    # bash \
    binutils \
    # binutils-gold (available in leap, but conflicts with binutils, will check if really needed, then add) \ 
    # libc6-compat (this package as I learnt, is to provide the necessary runtime libraries to make glibc-dependent programs work on Alpine, so might not be needed on sle based images?) \
    glibc \
    #curl \
    #file \
    #git \
    libseccomp-devel \
    #rsync \
    tar \
    make \
    gcc \
    # py-pip  \
    python3-pip; \
    zypper -n clean; \
    rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}

FROM build AS build-k8s-codegen
ARG TAG=v1.32.2-rke2r1-build20250213

COPY ./scripts/semver-parse.sh /semver-parse.sh
RUN chmod +x /semver-parse.sh

RUN echo $(/semver-parse.sh ${TAG} all)

COPY kubernetes-1.32.0.tar.gz .
RUN tar -xvzf kubernetes-1.32.0.tar.gz -C ${GOPATH}/src/kubernetes
WORKDIR ${GOPATH}/src/kubernetes

#RUN git clone -b $(/semver-parse.sh ${TAG} all) --depth=1 -- https://github.com/kubernetes/kubernetes.git ${GOPATH}/src/kubernetes


# COPY etcd-3.5.16.tar.gz .
# RUN tar -xvzf etcd-3.5.16.tar.gz && tar -xvzf vendor.tar.gz 
