# SPDX-License-Identifier: MIT

#     Copyright (c) 2025 SUSE LLC

# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon.

# The content of THIS FILE IS AUTOGENERATED and should not be manually modified.
# It is maintained by the BCI team and generated by
# https://github.com/SUSE/BCI-dockerfile-generator

# Please submit bugfixes or comments via https://bugs.opensuse.org/
# You can contact the BCI team via https://github.com/SUSE/bci/discussions

#!UseOBSRepositories

#!BuildTag: rancher/image-build-kubernetes:v1.32.2
#!BuildTag: rancher/image-build-kubernetes:latest
#!BuildName: image-build-kubernetes

ARG BCI_IMAGE=registry.suse.com/bci/bci-base:15.5
ARG GO_IMAGE=rancher/image-build-base:latest


FROM ${BCI_IMAGE} as bci
FROM ${GO_IMAGE} as build
RUN set -euo pipefail; \
    zypper -n install --no-recommends \
    # bash \
    binutils \
    # binutils-gold (available in leap, but conflicts with binutils, will check if really needed, then add) \ 
    # libc6-compat (this package as I learnt, is to provide the necessary runtime libraries to make glibc-dependent programs work on Alpine, so might not be needed on sle based images?) \
    glibc \
    #curl \
    #file \
    #git \
    libseccomp-devel \
    #rsync \
    tar \
    make \
    gcc \
    # py-pip  \
    python3-pip; \
    zypper -n clean; \
    rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}


FROM build AS build-k8s-codegen
ARG TAG

COPY ./scripts/semver-parse.sh /semver-parse.sh
RUN chmod +x /semver-parse.sh

RUN echo $(/semver-parse.sh ${TAG} all)
RUN git clone -b $(/semver-parse.sh ${TAG} all) --depth=1 -- https://github.com/kubernetes/kubernetes.git ${GOPATH}/src/kubernetes
WORKDIR ${GOPATH}/src/kubernetes

# force code generation
RUN make WHAT=cmd/kube-apiserver
# build statically linked executables 
RUN echo "export MAJOR=$(/semver-parse.sh ${TAG} major)" >> /usr/local/go/bin/go-build-static-k8s.sh
RUN echo "export MINOR=$(/semver-parse.sh ${TAG} minor)" >> /usr/local/go/bin/go-build-static-k8s.sh
RUN echo "export GIT_COMMIT=$(git rev-parse HEAD)" >> /usr/local/go/bin/go-build-static-k8s.sh
RUN echo "export KUBERNETES_VERSION=$(/semver-parse.sh ${TAG} k8s)" >> /usr/local/go/bin/go-build-static-k8s.sh
RUN echo "export BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> /usr/local/go/bin/go-build-static-k8s.sh
RUN echo "export GO_LDFLAGS=\"-linkmode=external \
    -X k8s.io/component-base/version.gitVersion=\${KUBERNETES_VERSION} \
    -X k8s.io/component-base/version.gitMajor=\${MAJOR} \
    -X k8s.io/component-base/version.gitMinor=\${MINOR} \
    -X k8s.io/component-base/version.gitCommit=\${GIT_COMMIT} \
    -X k8s.io/component-base/version.gitTreeState=clean \
    -X k8s.io/component-base/version.buildDate=\${BUILD_DATE} \
    -X k8s.io/client-go/pkg/version.gitVersion=\${KUBERNETES_VERSION} \
    -X k8s.io/client-go/pkg/version.gitMajor=\${MAJOR} \
    -X k8s.io/client-go/pkg/version.gitMinor=\${MINOR} \
    -X k8s.io/client-go/pkg/version.gitCommit=\${GIT_COMMIT} \
    -X k8s.io/client-go/pkg/version.gitTreeState=clean \
    -X k8s.io/client-go/pkg/version.buildDate=\${BUILD_DATE} \
    \"" >> /usr/local/go/bin/go-build-static-k8s.sh
RUN echo 'go-build-static.sh -gcflags=-trimpath=${GOPATH}/src/kubernetes -mod=vendor -tags=selinux,osusergo,netgo ${@}' \
    >> /usr/local/go/bin/go-build-static-k8s.sh
RUN chmod -v +x /usr/local/go/bin/go-*.sh


FROM build AS build-k8s-codegen
ARG TAG=v1.32.2-rke2r1-build20250213

COPY ./scripts/semver-parse.sh /semver-parse.sh
RUN chmod +x /semver-parse.sh

RUN echo $(/semver-parse.sh ${TAG} all) && mkdir -p ${GOPATH}/src/kubernetes

# COPY kubernetes-1.32.0.tar.gz .
COPY kubernetes-1.32.0 ${GOPATH}/src/kubernetes
COPY kubernetes.obsinfo ${GOPATH}/src/kubernetes/
# RUN tar -xvzf kubernetes-1.32.0.tar.gz --strip-components=1 -C ${GOPATH}/src/kubernetes
WORKDIR ${GOPATH}/src/kubernetes

RUN pwd && ls -la && git branch && git branch -r && git tag --list

# force code generation

RUN make WHAT=cmd/kube-apiserver
# build statically linked executables 
RUN echo "export MAJOR=$(/semver-parse.sh ${TAG} major)" >> /usr/local/bin/go-build-static-k8s.sh
RUN echo "export MINOR=$(/semver-parse.sh ${TAG} minor)" >> /usr/local/bin/go-build-static-k8s.sh
RUN echo "export GIT_COMMIT=$(git rev-parse HEAD)" >> /usr/local/bin/go-build-static-k8s.sh
RUN echo "export KUBERNETES_VERSION=$(/semver-parse.sh ${TAG} k8s)" >> /usr/local/bin/go-build-static-k8s.sh
RUN echo "export BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> /usr/local/bin/go-build-static-k8s.sh
RUN echo "export GO_LDFLAGS=\"-linkmode=external \
    -X k8s.io/component-base/version.gitVersion=\${KUBERNETES_VERSION} \
    -X k8s.io/component-base/version.gitMajor=\${MAJOR} \
    -X k8s.io/component-base/version.gitMinor=\${MINOR} \
    -X k8s.io/component-base/version.gitCommit=\${GIT_COMMIT} \
    -X k8s.io/component-base/version.gitTreeState=clean \
    -X k8s.io/component-base/version.buildDate=\${BUILD_DATE} \
    -X k8s.io/client-go/pkg/version.gitVersion=\${KUBERNETES_VERSION} \
    -X k8s.io/client-go/pkg/version.gitMajor=\${MAJOR} \
    -X k8s.io/client-go/pkg/version.gitMinor=\${MINOR} \
    -X k8s.io/client-go/pkg/version.gitCommit=\${GIT_COMMIT} \
    -X k8s.io/client-go/pkg/version.gitTreeState=clean \
    -X k8s.io/client-go/pkg/version.buildDate=\${BUILD_DATE} \
    \"" >> /usr/local/bin/go-build-static-k8s.sh
RUN echo 'go-build-static.sh -gcflags=-trimpath=${GOPATH}/src/kubernetes -mod=vendor -tags=selinux,osusergo,netgo ${@}' \
    >> /usr/local/bin/go-build-static-k8s.sh
RUN chmod -v +x /usr/local/bin/go-*.sh



#FROM build-k8s-codegen AS build-k8s
ARG K3S_ROOT_VERSION=v0.14.1

# ARG TARGETARCH=amd64
RUN if [ "$(uname -m)" == "x86_64" ]; then export TARGETARCH="amd64"; elif [ "$(uname -m)" == "aarch64" ]; then export TARGETARCH="arm64"; fi

RUN curl --output-dir /opt/k3s-root/ -O -L https://github.com/k3s-io/k3s-root/releases/download/v0.14.1/k3s-root-amd64.tar

RUN /opt/k3s-root/k3s-root-amd64.tar /opt/k3s-root/k3s-root.tar

# RUN curl --output-dir  /opt/k3s-root/k3s-root.tar -O -L https://github.com/k3s-io/k3s-root/releases/download/${K3S_ROOT_VERSION}/k3s-root-${TARGETARCH}.tar
RUN tar xvf /opt/k3s-root/k3s-root.tar -C /opt/k3s-root --wildcards --strip-components=2 './bin/aux/*tables*' './bin/aux/nft'
RUN tar xvf /opt/k3s-root/k3s-root.tar -C /opt/k3s-root './bin/ipset'

RUN go-build-static-k8s.sh -o bin/kube-apiserver          ./cmd/kube-apiserver
RUN go-build-static-k8s.sh -o bin/kube-controller-manager ./cmd/kube-controller-manager
RUN go-build-static-k8s.sh -o bin/kube-scheduler          ./cmd/kube-scheduler
RUN go-build-static-k8s.sh -o bin/kube-proxy              ./cmd/kube-proxy
RUN go-build-static-k8s.sh -o bin/kubeadm                 ./cmd/kubeadm
RUN go-build-static-k8s.sh -o bin/kubectl                 ./cmd/kubectl
RUN go-build-static-k8s.sh -o bin/kubelet                 ./cmd/kubelet
RUN go-assert-static.sh bin/*
RUN if [ "${TARGETARCH}" = "amd64" ]; then \
        go-assert-boring.sh bin/* ; \
    fi
RUN install -s bin/* /usr/local/bin/
RUN kube-proxy --version


FROM bci AS kubernetes
RUN zypper update -y && \
    zypper install -y which conntrack-tools kmod timezone awk
COPY --from=build-k8s-codegen /opt/k3s-root/aux/ /usr/sbin/
COPY --from=build-k8s-codegen /opt/k3s-root/bin/ /bin/
COPY --from=build-k8s-codegen /usr/local/bin/ /usr/local/bin/
